//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAgeFramework.Model.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbNewEntities : DbContext
    {
        public dbNewEntities()
            : base("name=dbNewEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblMaterial> tblMaterials { get; set; }
        public virtual DbSet<tblMaterialType> tblMaterialTypes { get; set; }
        public virtual DbSet<tblAreaCost> tblAreaCosts { get; set; }
        public virtual DbSet<tblBussinessCost> tblBussinessCosts { get; set; }
        public virtual DbSet<tblConsumable> tblConsumables { get; set; }
        public virtual DbSet<tblLengthCost> tblLengthCosts { get; set; }
        public virtual DbSet<tblVolumeCost> tblVolumeCosts { get; set; }
    }
}
