//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewAgeFramework.Model.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLengthCost
    {
        public int LenghtCostID { get; set; }
        public int TypeID { get; set; }
        public string MaterialID { get; set; }
        public Nullable<decimal> NoPieces { get; set; }
        public Nullable<decimal> LengthPerPiece { get; set; }
        public Nullable<decimal> TotalLength { get; set; }
        public Nullable<decimal> TotalCostPieces { get; set; }
        public Nullable<decimal> PricePerMeter { get; set; }
    
        public virtual tblMaterial tblMaterial { get; set; }
        public virtual tblMaterialType tblMaterialType { get; set; }
    }
}
